### ISSUE TITLE
tool is not loading package name list

### ISSUE THREAD

**Issue by dirtycoder0124** [NotSoSecure/android_application_analyzer#7] opened 2020-12-19 06:35 UTC
![not showing package list](https://user-images.githubusercontent.com/16449867/102682835-71149f00-41f2-11eb-9e54-e11d394c5874.jpg)

**Comment by g33kyshivam** [comment] 2020-12-20 18:51
Same issue over ubuntu 20.04 and genymotion

**Comment by dirtycoder0124** [comment] 2020-12-21 05:37
No solution far.

**Comment by g33kyshivam** [comment] 2020-12-21 05:49
![image](https://user-images.githubusercontent.com/24518185/102743746-1d36c100-437e-11eb-86c5-1a25c1fefbbd.png)
 I tried this tool over a real android device via ADB. There it works but in the screenshot, there is some sort of errors as well.

**Comment by dirtycoder0124** [comment] 2020-12-21 05:51
Is your phone rooted?

**Comment by g33kyshivam** [comment] 2020-12-21 06:10
Yes, it's rooted. Seems like the error of the screenshot I have attached is false positive as by default it loads the android package and checks if it has some content. The only issue is that somehow this tool is not working with genymotion or maybe we are missing something.

**Comment by dirtycoder0124** [comment] 2020-12-21 06:12
same here.

**Comment by devsecboy** [comment] 2020-12-21 06:19
Ack: Looking into the issue.

**Comment by devsecboy** [comment] 2020-12-23 15:50
@dirtycoder0124 @g33kyshivam The issue is fixed now!

Please download the latest repository and check!

**Comment by dirtycoder0124** [comment] 2020-12-23 15:52
Thank you for your response. I ll give it a try

Regards
Vipin Panchal

**Comment by devsecboy** [comment] 2021-07-06 05:29
Closing the issue due to inactivity if the issue still persists, please feel free to open a new issue

**Closed as completed by devsecboy** 2021-07-06 05:29 UTC
